### ISSUE TITLE
Support for writing applications in Rust 🦀

### ISSUE THREAD

**Issue by dcoles** [flipperdevices/flipperzero-firmware#1783]
As an application developer, I want to be able to write applications for the Flipper Zero in [Rust](https://www.rust-lang.org/).

Initially it's going to be easiest to support [`[#no-std]`](https://docs.rust-embedded.org/book/intro/no-std.html) applications, but the long-term goal would be to also support the [Rust standard library](https://doc.rust-lang.org/std/).

### Roadmap
- [x] Allow linking `#[no-std]` libraries to external applications: #1781
- [x] Low-level bindings for Furi/services: [`flipperzero-sys`](https://crates.io/crates/flipperzero-sys)
- [x] High level (a.k.a "safe") bindings for Furi/services: [`flipperzero`](https://crates.io/crates/flipperzero)
- [x] [`alloc`](https://doc.rust-lang.org/alloc/) support
- [x] Evaluate supporting the [Rust standard library](https://doc.rust-lang.org/std/)
- [ ] Developer documentation

### Anything else?

Rust for Flipper Zero now has its own GitHub project: [dcoles/flipperzero-rs](https://github.com/dcoles/flipperzero-rs)

**Comment by skotopes** [comment]
At this point we don't plan to support rust.

But we are going to accept PRs with some conditions:
- Rust runtime and standard library is not a part of firmware, it must be in elf itself
- General improvements to elf loader is ok, as long as they don't blowup internal flash usage

**Comment by dcoles** [comment]
@skotopes Hi! Thanks for the information. I wanted to make sure there was an feature request, since I'm sure there will be others interested.

Rust tends to statically link the runtime/standard library, so there's no need to add support into the firmware. Which is fine if this is just for external applications on the SD card.

Since we don't want to officially support Rust, I'll create a new GitHub project for Rust bindings to the Flipper Zero and push that to [crates.io](https://crates.io/). Developers of external applications can add this as a dependency to make it easier to call Furi and services API.

**Comment by dcoles** [comment]
Created [dcoles/flipperzero-rs](https://github.com/dcoles/flipperzero-rs) and published initial [`flipperzero`](https://crates.io/crates/flipperzero) and [`flipperzero-sys`](https://crates.io/crates/flipperzero-sys) crates.

**Comment by dcoles** [comment]
I think we can safely close this now that there's [flipperzero-rs/flipper-zero](https://github.com/flipperzero-rs/flipperzero).

While [`std`](https://doc.rust-lang.org/std/) support is probably possible, I'm not sure it's worth the trouble at present (the Flipper Zero SDK is distinct enough from a Unix-style platform that it would require a full port).

**Comment by skotopes** [comment]
@dcoles Good job guys, really awesome to see such achievements.

**Comment by dcoles** [comment]
@skotopes Thanks! The SDK support has certainly made life a lot easier. The main challenge now is making the Clang-based [`bindgen`](https://crates.io/crates/bindgen) play nicely with the toolchain. Once that's reasonably stable, then we can make the [`flipperzero-sys`](https://crates.io/crates/flipperzero-sys) crate support multiple SDK versions so folks don't have to wait for me to regenerate the bindings.
