### ISSUE TITLE
UI: icons, animation, standard widgets

### ISSUE THREAD

**Issue by skotopes** [flipperdevices/flipperzero-firmware#190]
# ToDo

- [x] Icon Makefile
- [x] Icon Registry
- [x] Icons
- [x] Animation
- [x] Icon rendering
- [x] Widget lifecycle (alloc/free)
- [x] Animation rendering
- [x] Application icons in menu
- [x] Status bar icons(apps)
- [x] Standard Widgets for dialogs and etc
