### ISSUE TITLE
Welcome from Strokov Andrew

### ISSUE THREAD

**Issue by glitchcore** [flipperdevices/flipperzero-firmware#32]
# About me

* embedded FW and schematic developer
* C — good level, Rust, C++ — medium level
* Many experience with hardware debugging, RF, analog and digital schematic

You can find more information at [strokov.org](https://strokov.org)

# What tasks I can take

- [ ] organizing people to make environment: CI/CD, github, some integrations (no estimate)
- [ ] choose core technology (#17) (no estimate)
- [ ] making FURI: tool for control application flow and making dynamically linked interaction between app. (#14) (~16 h)
- [ ] Create API documentation and examples (#15) (~20 h)
- [ ] Add old prototype code (~8 h)
- [ ] Writing wiki pages for core and features (no estimate)

# What I need

I need help from people who know how to setup team development on GitHub, some devops skills to make CI/testing and automation.
