### ISSUE TITLE
Welcome from Philip

### ISSUE THREAD

**Issue by officialdarksheao** [flipperdevices/flipperzero-firmware#39]
# About Me
* Web and Application engineer, working with tech stacks using c, c++, c#, Java, PHP and node
* regularly configuring docker images and integrating ci/cd
* some industrial prototyping experience using the Arduino stack

 # What tasks I can take
- [ ] #12 Linting/Codestyle, integrations with [clang format](https://clang.llvm.org/docs/ClangFormat.html)  or [artistic style](http://astyle.sourceforge.net/) for c stack, [rustc linting](https://doc.rust-lang.org/rustc/lints/levels.html) OR an alternative rust linter, for automated style checks on pull requests and a docker image that can be used to watch local codebases and auto-format if desired. Code style must be defined for implementing with these tools. (25 hours after style defined)
- [ ] #26 Unit testing stack, using make for unit tests and writing wiki pages on unit testing guides, integration into github pipeline for verification, and optionally code to determine newly added functions in pull requests and warn or reject if unit tests not added (no estimate overall, initial setup and guides ~20 hours, verification rules for new code without unit tests would be deterministic on what is decided is reasonable)
- [ ] #26 Smoke testing, I could write a python or ruby script fairly quickly to interact and parse through standard i/o for at least rudimentary smoke testing (8 hours) This process could be integrated with automated CI to smoke test firmware on pull requests. (8 hours)
- [ ] #26 Integration/Hardware testing, I suggesting using a control board, my preferred would be Arduino, to connect to and interact with the hardware pins with the firmware in a "testing" mode so extra debug messages and user/sensor input simulations could be communicated with the control board, and through serial into a docker based testing service. Integrations between this and the front end of a hardware emulator would be awesome to get the simulated input polished. (no estimate)
- [ ] #29 Rust additions to build image, I am very new to rust but I am experienced with adding capabilities to docker images. Adding rust support, cargo, test code, cbindgen: (16 hours) Integrating with current building: (no estimate, would need to complete prerequisite setup and would have a better idea of time then)

# What help do you need
I lack experience in doing hardware emulation and I am very new to rust. Determining and setting up the code style would be something I would want the team to determine and agree on, what one thinks is best code style can differ greatly. The concept of "acceptable code coverage" is subjective, too high and it discourages change, too low and things get sloppy, so that would need to be discussed.
